### ISSUE TITLE
Force close

### ISSUE THREAD

**Issue by hunterscop1** [shub39/Rush#55]
The rush app is force close on my Android 15 devices, idk why

**Comment by hunterscop1** [comment]
time: 1732455073587
msg: java.lang.SecurityException: Remote stack trace:
	at com.android.server.media.MediaSessionService.enforceMediaPermissions(MediaSessionService.java:893)
	at com.android.server.media.MediaSessionService.-$$Nest$menforceMediaPermissions(MediaSessionService.java:0)
	at com.android.server.media.MediaSessionService$SessionManagerImpl.verifySessionsRequest(MediaSessionService.java:2435)
	at com.android.server.media.MediaSessionService$SessionManagerImpl.addSessionsListener(MediaSessionService.java:1617)
	at android.media.session.ISessionManager$Stub.onTransact(ISessionManager.java:437)
stacktrace: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.shub39.rush/com.shub39.rush.MainActivity}: java.lang.SecurityException: Missing permission to control media.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4048)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4235)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:112)
	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:174)
	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:109)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:81)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2636)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8705)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
Caused by: java.lang.SecurityException: Missing permission to control media.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3246)
	at android.os.Parcel.createException(Parcel.java:3230)
	at android.os.Parcel.readException(Parcel.java:3213)
	at android.os.Parcel.readException(Parcel.java:3155)
	at android.media.session.ISessionManager$Stub$Proxy.addSessionsListener(ISessionManager.java:834)
	at android.media.session.MediaSessionManager.addOnActiveSessionsChangedListener(MediaSessionManager.java:389)
	at android.media.session.MediaSessionManager.addOnActiveSessionsChangedListener(MediaSessionManager.java:337)
	at android.media.session.MediaSessionManager.addOnActiveSessionsChangedListener(MediaSessionManager.java:318)
	at u2.e.b(Unknown Source:47)
	at com.shub39.rush.MainActivity.onCreate(Unknown Source:35)
	at android.app.Activity.performCreate(Activity.java:9002)
	at android.app.Activity.performCreate(Activity.java:8980)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1532)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4030)
	... 13 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.media.MediaSessionService.enforceMediaPermissions(MediaSessionService.java:893)
	at com.android.server.media.MediaSessionService.-$$Nest$menforceMediaPermissions(MediaSessionService.java:0)
	at com.android.server.media.MediaSessionService$SessionManagerImpl.verifySessionsRequest(MediaSessionService.java:2435)
	at com.android.server.media.MediaSessionService$SessionManagerImpl.addSessionsListener(MediaSessionService.java:1617)
	at android.media.session.ISessionManager$Stub.onTransact(ISessionManager.java:437)

That's the bug log if needed

**Comment by shub39** [comment]
Seems like a permissions error I'll look into it later. Meanwhile have you turned the notification access permission off?

**Comment by hunterscop1** [comment]
Nvm, I think that's something wrong with my devices, and now it working perfectly fine

**Comment by shub39** [comment]
I see, closing this then

**Comment by RunningDroid** [comment]
I came across this bug as well, Rush started crashing on launch after I updated from 2.3.7 to 2.3.8.
I fixed it by:
1. making a backup (via `adb backup com.shub39.rush`)
2. clearing the app's Storage
3. opening and closing the app (might not be needed, I just wanted to make sure it worked)
4. restoring the backup (`adb restore backup.ab`)

I figure something that's in the app's storage but not part of the app's backup got corrupted somehow.
I'm using a OnePlus 7 Pro running Android 11, if it helps.

logcat from launch to crash:
https://gist.github.com/RunningDroid/dcf69cd0f15a94c2206dc48da099b56a

**Comment by RunningDroid** [comment]
I hit this again after updating from 3.6.0 to 4.0.0, same phone, slightly more obfuscated logcat :
https://gist.github.com/RunningDroid/80581a7ab70e6dc4b21d7851804ebafa

I fixed it with the same steps as last time, I tried Downgrading and Updating again but I couldn't get it to break again.

**Comment by shub39** [comment]
This is a very trivial issue with android 16+ as they changed how mediasessionmanager is accessed in android 16.  I can't replicate this crash in a deterministic way
